<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PlatformTarget>x64</PlatformTarget>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishSingleFile>true</PublishSingleFile>
		<Version>1.6.0</Version>
		<SelfContained>false</SelfContained>
		<PublishTrimmed>false</PublishTrimmed>
		<AssemblyName>Updater</AssemblyName>
		<LangVersion>latest</LangVersion>
		
		<CodePage>65001</CodePage>
		<!-- 添加这一行以确保使用 UTF-8 编码 -->
	</PropertyGroup>

	<ItemGroup>
	  <!--<PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.3" />-->
	  <PackageReference Include="UTF.Unknown" Version="2.5.1" />
	</ItemGroup>

</Project>
