name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Create update.zip
      run: |
        cd publish
        zip -r ../update.zip .

    - name: Generate version number
      id: generate_version
      run: echo "::set-output name=version::$(date +'%Y%m%d%H%M%S')"

    - name: Generate update_info.json
      run: |
        echo '{
          "version": "${{ steps.generate_version.outputs.version }}",
          "updateUrl": "https://github.com/username/repository/releases/download/v${{ steps.generate_version.outputs.version }}/update.zip"
        }' > update_info.json

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: update-package
        path: update.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.generate_version.outputs.version }}
        release_name: Release v${{ steps.generate_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload update.zip to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./update.zip
        asset_name: update.zip
        asset_content_type: application/zip

    - name: Upload update_info.json to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./update_info.json
        asset_name: update_info.json
        asset_content_type: application/json
